default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  host: 127.0.0.1
  username: pguser
  password: pguser

development:
  <<: *default
  database: umbrellio_dev

test:
  <<: *default
  database: umbrellio_test

production:
  <<: *default
  database: umbrellio
